
import type { Pet } from './types';

export const INITIAL_PETS: Pet[] = [
  {
    id: 1,
    name: 'Rocky',
    type: 'dog',
    breed: 'Mestizo',
    age: '2 years',
    size: 'Medium',
    location: 'Buenos Aires',
    imageUrl: 'https://picsum.photos/seed/rocky/600/600',
  },
  {
    id: 2,
    name: 'Luna',
    type: 'cat',
    breed: 'Domestic Shorthair',
    age: '1 year',
    size: 'Small',
    location: 'Córdoba',
    imageUrl: 'https://picsum.photos/seed/luna/600/600',
  },
  {
    id: 3,
    name: 'Max',
    type: 'dog',
    breed: 'German Shepherd Mix',
    age: '4 years',
    size: 'Large',
    location: 'Rosario',
    imageUrl: 'https://picsum.photos/seed/max/600/600',
  },
  {
    id: 4,
    name: 'Milo',
    type: 'cat',
    breed: 'Siamese Mix',
    age: '3 years',
    size: 'Medium',
    location: 'Mendoza',
    imageUrl: 'https://picsum.photos/seed/milo/600/600',
  },
  {
    id: 5,
    name: 'Bella',
    type: 'dog',
    breed: 'Golden Retriever Mix',
    age: '6 months',
    size: 'Medium',
    location: 'La Plata',
    imageUrl: 'https://picsum.photos/seed/bella/600/600',
  },
  {
    id: 6,
    name: 'Simba',
    type: 'cat',
    breed: 'Domestic Longhair',
    age: '5 years',
    size: 'Large',
    location: 'Mar del Plata',
    imageUrl: 'https://picsum.photos/seed/simba/600/600',
  },
  {
    id: 7,
    name: 'Coco',
    type: 'dog',
    breed: 'Poodle Mix',
    age: '3 years',
    size: 'Small',
    location: 'Tucumán',
    imageUrl: 'https://picsum.photos/seed/coco/600/600',
  },
  {
    id: 8,
    name: 'Nala',
    type: 'cat',
    breed: 'Tabby',
    age: '2 years',
    size: 'Medium',
    location: 'Salta',
    imageUrl: 'https://picsum.photos/seed/nala/600/600',
  },
   {
    id: 9,
    name: 'Toby',
    type: 'dog',
    breed: 'Labrador Mix',
    age: '5 years',
    size: 'Large',
    location: 'Buenos Aires',
    imageUrl: 'https://picsum.photos/seed/toby/600/600',
  },
  {
    id: 10,
    name: 'Cleo',
    type: 'cat',
    breed: 'Calico',
    age: '1.5 years',
    size: 'Small',
    location: 'Córdoba',
    imageUrl: 'https://picsum.photos/seed/cleo/600/600',
  },
  {
    id: 11,
    name: 'Zeus',
    type: 'dog',
    breed: 'Boxer Mix',
    age: '6 years',
    size: 'Large',
    location: 'Rosario',
    imageUrl: 'https://picsum.photos/seed/zeus/600/600',
  },
  {
    id: 12,
    name: 'Olivia',
    type: 'cat',
    breed: 'Tuxedo',
    age: '8 months',
    size: 'Small',
    location: 'Mendoza',
    imageUrl: 'https://picsum.photos/seed/olivia/600/600',
  },
];
